

CREATE TABLE IF NOT EXISTS COMMENTS (name TEXT NOT NULL PRIMARY KEY NOT NULL, email TEXT NOT NULL, comment TEXT);

DELETE FROM COMMENTS;

INSERT INTO COMMENTS VALUES ('Caitlin', 'caitlin.graves@wsu.edu', 'this is a comment');
